#!/usr/bin/sh
#
# wm independent hotkeys
#
. "${HOME}/.cache/wal/colors.sh"

# terminal emulator
super + Return
  urxvtc

# program launcher
super + d
  ~/.config/dmen.sh

#dmenu_run -fn 'GohuFont-14' -nb "$color0" -nf "$color15" -sb "$color1" -sf "$color15"
#dmenu_run -fn 'GohuFont-14' -sb $focus_color -sf $fg_color -nf $fg_color -nb $bg_color
#rofi -show run

super + w
  tdrop -w -10 -h 20% -a urxvtc

# make sxhkd reload its configuration files:
super + Escape
	pkill -USR1 -x sxhkd

#
# bspwm hotkeys
#

# quit bspwm normally
super + alt + Escape
	bspc quit

# close and kill
super + shift + q
	bspc node -c

# alternate between the tiled and monocle layout
super + f
	bspc desktop -l next

# if the current node is automatic, send it to the last manual, otherwise pull the last leaf
#super + y
#	bspc query -N -n focused.automatic && bspc node -n last.!automatic || bspc node last.leaf -n focused

# swap the current node and the biggest node
super + g
	bspc node -s biggest

#
# state/flags
#

# set the window state
super + {t,shift + t,s,f}
	bspc node -t {tiled,pseudo_tiled,floating,fullscreen}

# set the node flags
super + {z,x,c}
	bspc node -g {locked,private,sticky}

#
# focus/swap
#

# focus the node in the given direction
super + {_,shift + }{h,j,k,l}
	bspc node -{f,s} {west,south,north,east}

# focus the node for the given path jump
#super + {p,b,comma,period}
#	bspc node -f @{parent,brother,first,second}

# focus the next/previous node in the current desktop
#super + {_,shift + }c
#	bspc node -f {next,prev}.local

# focus the next/previous desktop in the current monitor
#super + bracket{left,right}
#	bspc desktop -f {prev,next}.local

# focus the last node/desktop
super + {grave,Tab}
	bspc {node,desktop} -f last

# focus the older or newer node in the focus history
#super + {o,i}
#	bspc wm -h off; \
#	bspc node {older,newer} -f; \
#	bspc wm -h on

# focus or send to the given desktop
super + {_,shift + }{1-9,0}
	bspc {desktop -f,node -d} '^{1-9,10}'

#
# preselect
#

# preselect the direction
super + ctrl + {h,j,k,l}
	bspc node -p {west,south,north,east}

# preselect the ratio
super + ctrl + {1-9}
	bspc node -o 0.{1-9}

# cancel the preselection for the focused node
super + ctrl + space
	bspc node -p cancel

#
# move/resize
#

# Change window gap
super + {minus,equal}
  bspc config -d focused window_gap $((`bspc config -d focused window_gap` {+,-} 2 ))

# expand a window by moving one of its side outward
super + alt + {h,j,k,l}
	bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

# contract a window by moving one of its side inward
super + alt + ctrl + {h,j,k,l}
	bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

# move a floating window
super + {Left,Down,Up,Right}
	bspc node -v {-20 0,0 20,0 -20,20 0}

# insert receptacle, or clear receptacles on current desktop
super + {_,shift} + r
  insert={true,false}; $insert && bspc node -i || for win in `bspc query -N -n .leaf.!window`; do bspc node $win -k ; done;


