#! /bin/sh

# __
#/\ \
#\ \ \____   ____  _____   __  __  __   ___ ___   _ __  ___
# \ \ '__`\ /',__\/\ '__`\/\ \/\ \/\ \/' __` __`\/\`'__/'___\
#  \ \ \L\ /\__, `\ \ \L\ \ \ \_/ \_/ /\ \/\ \/\ \ \ \/\ \__/
#   \ \_,__\/\____/\ \ ,__/\ \___x___/\ \_\ \_\ \_\ \_\ \____\
#    \/___/ \/___/  \ \ \/  \/__//__/  \/_/\/_/\/_/\/_/\/____/
#                    \ \_\
#                     \/_/

#export BSPWM_INITIAL_STATE="/home/kumomi/.config/bspwm/bspwm-initial_state.json"
#bspc wm -l "$BSPWM_INITIAL_STATE"
bspc monitor -d I II III IV V VI
. "${HOME}/.cache/wal/colors.sh"

# Looks
bspc config initial_polarity second_child
bspc config focus_follows_pointer true
bspc config border_width        5
bspc config window_gap 50
bspc config bottom_padding 10
bspc config split_ratio          0.50
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_border_color "$color1"
bspc config presel_feedback_color "$color1"
#bspc config active_border_color "$focus_color"
#bspc config normal_border_color "$bg_color"
#bspc config focused_border_color "$focus_color"
#bspc config presel_feedback_color "$focus_color"
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config paddingless_monocle  true

# Placement rules
#bspc rule -a chromium -o node=@^1:^1:/
##bspc rule -a Vivaldi-stable -o node=@^1:^1:/
#bspc rule -a mpv:dnc -o node=@^1:^2:/1/2/1
#bspc rule -a URxvt:music -o node=@^1:^2:/2/1/2
#bspc rule -a URxvt:ranger -o node=@^1:^3:/1
#bspc rule -a URxvt:main -o node=@^1:^3:/2/1
#bspc rule -a URxvt:main1 -o node=@^1:^3:/2/2

# General rules
bspc rule -a chromium desktop=^1
bspc rule -a mpv state=floating
bspc rule -a Sxiv state=floating
bspc rule -a Zathura state=tiled
bspc rule -a mpv:dnc state=pseudo_tiled desktop=^2
bspc rule -a URxvt:music state=pseudo_tiled desktop=^2

# AutoStart
wal -a 90 -l -g -i /home/kumomi/pics/walls/dusa.png
killall dunst;~/.config/scripts/startdunst.sh &
mpd .config/mpd/mpd.conf &
.config/scripts/mpdnotify start &
chromium &
#urxvtc -name music -e ncmpcpp &
#mpv -name dnc --ao=null /media/windows/cloud/pics/girls/dance/15133657204850.webm &
#urxvtc -name main &
#urxvtc -name main1 &
#urxvtc -name ranger -e ranger &
sh ~/.config/polybar/launch.sh &
#sh ~/.config/scripts/wall.sh
